package numbersystemconverter;
/*
 * This Java source file was generated by the Gradle 'init' task.
 * 63-bit char number system conver 
 */

public class App {
    public static void main(String[] args) {
        new MainFrame();
    }
}

